name: qualitychecks

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  abaplint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install abaplint
      run: npm install -g @abaplint/cli
    - name: Run abaplint
      run: abaplint